spring:
  application:
    name: access-control-example
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/laboratory
    username: root
    password: travis
  jpa:
    hibernate:
      ddl-auto: create-drop
