spring:
  application:
    name: access-control-example
  datasource:
    url: jdbc:mysql://localhost:3306/laboratory
    username: db_user
    password: db_password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
