spring:
  application:
    name: access-control-example
  datasource:
    url: jdbc:mysql://localhost:3306/laboratory
    username: db_user
    password: db_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
